/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-15 04:07:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop.cs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.petshop.model.domain.Review;
import com.koreait.petshop.model.domain.Member;
import com.koreait.petshop.model.domain.Product;

public final class regist_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../../inc/shop_navi.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../../inc/footer.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../../inc/header.jsp", Long.valueOf(1610679240000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Review");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Member");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	Review review =(Review)request.getAttribute("review");
	Member member =(Member)session.getAttribute("member");//회원에 대한 정보
	Product product =(Product)request.getAttribute("product");//내가 본 상품 번호
	//out.print("member:"+member);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("\n");
      out.write("    <!-- Title  -->\n");
      out.write("    <title>Karl - Fashion Ecommerce Template | Home</title>\n");
      out.write("\t");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"Ashion Template\">\n");
      out.write("    <meta name=\"keywords\" content=\"Ashion, unica, creative, html\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Ashion | Petshop</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\"\n");
      out.write("    rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Css Styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/elegant-icons.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("     <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js\"></script>\n");
      out.write("    ");
      out.write("\n");
      out.write("\t<style>\n");
      out.write("\t\tinput[type=text], select, textarea {\n");
      out.write("\t\t  width: 100%;\n");
      out.write("\t\t  padding: 12px;\n");
      out.write("\t\t  border: 1px solid #ccc;\n");
      out.write("\t\t  border-radius: 4px;\n");
      out.write("\t\t  box-sizing: border-box;\n");
      out.write("\t\t  margin-top: 6px;\n");
      out.write("\t\t  margin-bottom: 16px;\n");
      out.write("\t\t  resize: vertical;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput[type=button],button {\n");
      out.write("\t\t  background-color: #4CAF50;\n");
      out.write("\t\t  color: white;\n");
      out.write("\t\t  padding: 12px 20px;\n");
      out.write("\t\t  border: none;\n");
      out.write("\t\t  border-radius: 4px;\n");
      out.write("\t\t  cursor: pointer;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput[type=button]:hover {\n");
      out.write("\t\t  background-color: #45a049;\n");
      out.write("\t\t}\t\n");
      out.write("\t.container {\n");
      out.write("\t  border-radius: 5px;\n");
      out.write("\t  background-color: #f2f2f2;\n");
      out.write("\t  padding: 20px;\n");
      out.write("\t}\n");
      out.write("\t</style>\t\n");
      out.write("\t<script>\n");
      out.write("\t\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$($(\"input[type='button']\")[0]).click(function(){\n");
      out.write("\t\t\tregist();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\tfunction regist(){\n");
      out.write("\t\t\t$(\"#reviewForm\").attr({\n");
      out.write("\t\t\t\taction:\"/shop/cs/regist\",\n");
      out.write("\t\t\t\tmethod:\"post\"\n");
      out.write("\t\t\t});\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#reviewForm\").submit();\n");
      out.write("\t\t}\n");
      out.write("\t</script>\t\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    \t");
      out.write("\n");
      out.write("<!-- Page Preloder -->\n");
      out.write("\n");
      out.write(" <!-- Offcanvas Menu Begin -->\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\n");
      out.write("        <div class=\"offcanvas__close\">+</div>\n");
      out.write("        <ul class=\"offcanvas__widget\">\n");
      out.write("            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("            <li><a href=\"/shop/cart/list\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"offcanvas__logo\">\n");
      out.write("            <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\n");
      out.write("        <div class=\"offcanvas__auth\">\n");
      out.write("            <a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("            <a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Offcanvas Menu End -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-3 col-lg-2\">\n");
      out.write("                    <div class=\"header__logo\">\n");
      out.write("                        <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xl-6 col-lg-7\">\n");
      out.write("                    <nav class=\"header__menu\">\n");
      out.write("                        <ul>\n");
      out.write("                        \t<li></li>\n");
      out.write("                            <li class=\"active\"><a href=\"/\">Home</a></li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">옷</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=1\">패딩</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=2\">나시</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=3\">점프수트</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=4\">원피스</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">사료</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=5\">연어</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=6\">소고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=7\">양고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=8\">닭고기</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">간식</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=9\">츄잉껌</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=10\">츄르</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=11\">소시지</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=12\">육포말이</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">악세서리</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=13\">모자</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=14\">목걸이</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=15\">펫스텝</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=16\">철망</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <!-- <li><a href=\"/\">Shop</a></li> -->\n");
      out.write("                            <li><a href=\"/shop/cart/list\">Cart</a>\n");
      out.write("                               <!--  <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"./product-details.html\">Product Details</a></li>\n");
      out.write("                                     <li><a href=\"/shop/cart/list\">Cart</a></li>\n");
      out.write("                                    <li><a href=\"./checkout.html\">Checkout</a></li>\n");
      out.write("                                    <li><a href=\"./blog-details.html\">Blog Details</a></li>\n");
      out.write("                            <li><a href=\"./blog.html\">Blog</a></li>\n");
      out.write("                            <li><a href=\"./contact.html\">Contact</a></li>\n");
      out.write("                                </ul> -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"col-lg-3\">\n");
      out.write("                    <div class=\"header__right\">\n");
      out.write("                        <div class=\"header__right__auth\">\n");
      out.write("                            ");
if(session.getAttribute("member")==null){ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("                            \t<a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("            \t\t\t\t");
}else{ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/logout\">LogOut</a>\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/mypage_order\">MyPage</a>\n");
      out.write("        \t\t\t\t\t");
} 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <ul class=\"header__right__widget\">\n");
      out.write("                            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"canvas__open\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Section End -->");
      out.write("\n");
      out.write("        <!-- ****** Top Discount Area End ****** -->\n");
      out.write("\t\t<div class=\"container\">   \n");
      out.write("\t\t  <form id=\"reviewForm\">\n");
      out.write("\n");
      out.write("\t\t  \t<label>MemberID</label>\n");
      out.write("\t\t    ");
      out.write("\n");
      out.write("\t\t    <input type=\"hidden\" name=\"member_id\" value=\"");
      out.print(member.getMember_id());
      out.write("\">\n");
      out.write("\t\t    <input type=\"text\"  value=\"");
      out.print(member.getUser_id());
      out.write("\">\n");
      out.write("\t\t    \n");
      out.write("\t\t    <label>Write</label>\n");
      out.write("\t\t    <textarea name=\"reviews\" placeholder=\"후기를 입력란\" style=\"height:200px\"></textarea>\n");
      out.write("\t\t    <input type=\"hidden\" name=\"product_id\" value=\"");
      out.print(product.getProduct_id() );
      out.write("\" >\n");
      out.write("\t\t    <input type=\"button\" value=\"regist\">\n");
      out.write("\t\t    <input type=\"button\" value=\"list\" onClick=\"location.href='/shop/product/detail?product_id=");
      out.print(product.getProduct_id());
      out.write("';\">\n");
      out.write("\t\t  </form>\n");
      out.write("\t</div>\t\n");
      out.write("        <!-- ****** Footer Area Start ****** -->\n");
      out.write("        ");
      out.write("\n");
      out.write("<!-- Js Plugins -->\n");
      out.write("<script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/mixitup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.countdown.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.slicknav.js\"></script>\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.nicescroll.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("        <!-- ****** Footer Area End ****** -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.wrapper end -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
