/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-12 04:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop.cs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.fashionshop.model.domain.SubCategory;
import com.koreait.fashionshop.model.domain.TopCategory;
import java.util.List;

public final class registForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../inc/header.jsp", Long.valueOf(1609823453230L));
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../inc/footer.jsp", Long.valueOf(1609820507840L));
    _jspx_dependants.put("/WEB-INF/views/shop/cs/../inc/top.jsp", Long.valueOf(1610412520978L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.koreait.fashionshop.model.domain.SubCategory");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.koreait.fashionshop.model.domain.TopCategory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("\n");
      out.write("    <!-- Title  -->\n");
      out.write("    <title>Karl - Fashion Ecommerce Template | Home</title>\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- Favicon  -->\r\n");
      out.write("<link rel=\"icon\" href=\"/resources/img/core-img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Core Style CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/core-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Responsive CSS -->\r\n");
      out.write("<link href=\"/resources/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\t<style>\n");
      out.write("\t\tinput[type=text], select, textarea {\n");
      out.write("\t\t  width: 100%;\n");
      out.write("\t\t  padding: 12px;\n");
      out.write("\t\t  border: 1px solid #ccc;\n");
      out.write("\t\t  border-radius: 4px;\n");
      out.write("\t\t  box-sizing: border-box;\n");
      out.write("\t\t  margin-top: 6px;\n");
      out.write("\t\t  margin-bottom: 16px;\n");
      out.write("\t\t  resize: vertical;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput[type=button] {\n");
      out.write("\t\t  background-color: #4CAF50;\n");
      out.write("\t\t  color: white;\n");
      out.write("\t\t  padding: 12px 20px;\n");
      out.write("\t\t  border: none;\n");
      out.write("\t\t  border-radius: 4px;\n");
      out.write("\t\t  cursor: pointer;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tinput[type=button]:hover {\n");
      out.write("\t\t  background-color: #45a049;\n");
      out.write("\t\t}\t\n");
      out.write("\t.container {\n");
      out.write("\t  border-radius: 5px;\n");
      out.write("\t  background-color: #f2f2f2;\n");
      out.write("\t  padding: 20px;\n");
      out.write("\t}\n");
      out.write("\t</style>\t\n");
      out.write("\t<script>\n");
      out.write("\t\t$(function(){\n");
      out.write("\t\t\t$($(\"input[type='button']\")[0]).click(function(){\n");
      out.write("\t\t\t\tregist();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tfunction regist(){\n");
      out.write("\t\t\t$(\"#qnaForm\").attr({\n");
      out.write("\t\t\t\taction:\"/shop/cs/qna/regist\",\n");
      out.write("\t\t\t\tmethod:\"post\"\n");
      out.write("\t\t\t});\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#qnaForm\").submit();\n");
      out.write("\t\t}\n");
      out.write("\t</script>\t\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<TopCategory> topList = (List)request.getAttribute("topList");

      out.write("\r\n");
      out.write("<div class=\"catagories-side-menu\">\r\n");
      out.write("        <!-- Close Icon -->\r\n");
      out.write("        <div id=\"sideMenuClose\">\r\n");
      out.write("            <i class=\"ti-close\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--  Side Nav  -->\r\n");
      out.write("        <div class=\"nav-side-menu\">\r\n");
      out.write("            <div class=\"menu-list\">\r\n");
      out.write("                <h6>Categories</h6>\r\n");
      out.write("                <ul id=\"menu-content\" class=\"menu-content collapse out\">\r\n");
      out.write("                    <!-- Single Item -->\r\n");
      out.write("                    ");
for(int i=0;i<topList.size();i++){ 
      out.write("\r\n");
      out.write("                    ");
TopCategory topCategory=topList.get(i); 
      out.write("\r\n");
      out.write("                    <li data-toggle=\"collapse\" data-target=\"#");
      out.print(topCategory.getTopcategory_id() );
      out.write("\" class=\"collapsed active\">\r\n");
      out.write("                        <a href=\"#\">");
      out.print(topCategory.getName() );
      out.write("<span class=\"arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"sub-menu collapse\" id=\"");
      out.print(topCategory.getTopcategory_id());
      out.write("\">\r\n");
      out.write("                        \t");
for(int a=0;a<topCategory.getSubCategory().size();a++){ 
      out.write("\r\n");
      out.write("                        \t");
SubCategory subCategory=topCategory.getSubCategory().get(a);
      out.write("\r\n");
      out.write("                            <li><a href=\"#\">");
      out.print(subCategory.getName() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>       \r\n");
      out.write("                    ");
} 
      out.write("          \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- ****** Header Area Start ****** -->\r\n");
      out.write("        <header class=\"header_area\">\r\n");
      out.write("            <!-- Top Header Area Start -->\r\n");
      out.write("            <div class=\"top_header_area\">\r\n");
      out.write("                <div class=\"container h-100\">\r\n");
      out.write("                    <div class=\"row h-100 align-items-center justify-content-end\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-7\">\r\n");
      out.write("                            <div class=\"top_single_area d-flex align-items-center\">\r\n");
      out.write("                                <!-- Logo Area -->\r\n");
      out.write("                                <div class=\"top_logo\">\r\n");
      out.write("                                    <a href=\"#\"><img src=\"/resources/img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Cart & Menu Area -->\r\n");
      out.write("                                <div class=\"header-cart-menu d-flex align-items-center ml-auto\">\r\n");
      out.write("                                    <!-- Cart Area -->\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"#\" id=\"header-cart-btn\" target=\"_blank\"><span class=\"cart_quantity\">2</span> <i class=\"ti-bag\"></i> Your Bag $20</a>\r\n");
      out.write("                                        <!-- Cart List Area Start -->\r\n");
      out.write("                                        <ul class=\"cart-list\">\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\" class=\"image\"><img src=\"/resources/img/product-img/product-10.jpg\" class=\"cart-thumb\" alt=\"\"></a>\r\n");
      out.write("                                                <div class=\"cart-item-desc\">\r\n");
      out.write("                                                    <h6><a href=\"#\">Women's Fashion</a></h6>\r\n");
      out.write("                                                    <p>1x - <span class=\"price\">$10</span></p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <span class=\"dropdown-product-remove\"><i class=\"icon-cross\"></i></span>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\" class=\"image\"><img src=\"/resources/img/product-img/product-11.jpg\" class=\"cart-thumb\" alt=\"\"></a>\r\n");
      out.write("                                                <div class=\"cart-item-desc\">\r\n");
      out.write("                                                    <h6><a href=\"#\">Women's Fashion</a></h6>\r\n");
      out.write("                                                    <p>1x - <span class=\"price\">$10</span></p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <span class=\"dropdown-product-remove\"><i class=\"icon-cross\"></i></span>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"total\">\r\n");
      out.write("                                                <span class=\"pull-right\">Total: $20.00</span>\r\n");
      out.write("                                                <a href=\"cart.html\" class=\"btn btn-sm btn-cart\">Cart</a>\r\n");
      out.write("                                                <a href=\"checkout-1.html\" class=\"btn btn-sm btn-checkout\">Checkout</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"header-right-side-menu ml-15\">\r\n");
      out.write("                                        <a href=\"#\" id=\"sideMenuBtn\"><i class=\"ti-menu\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Top Header Area End -->\r\n");
      out.write("            <div class=\"main_header_area\">\r\n");
      out.write("                <div class=\"container h-100\">\r\n");
      out.write("                    <div class=\"row h-100\">\r\n");
      out.write("                        <div class=\"col-12 d-md-flex justify-content-between\">\r\n");
      out.write("                            <!-- Header Social Area -->\r\n");
      out.write("                            <div class=\"header-social-area\">\r\n");
      out.write("                                <a href=\"#\"><span class=\"karl-level\">Share</span> <i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Menu Area : 메인네비게이션 영역 -->\r\n");
      out.write("                            <div class=\"main-menu-area\">\r\n");
      out.write("                                <nav class=\"navbar navbar-expand-lg align-items-start\">\r\n");
      out.write("\r\n");
      out.write("                                    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#karl-navbar\" aria-controls=\"karl-navbar\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"><i class=\"ti-menu\"></i></span></button>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"collapse navbar-collapse align-items-start collapse\" id=\"karl-navbar\">\r\n");
      out.write("                                        <ul class=\"navbar-nav animated\" id=\"nav\">\r\n");
      out.write("                                            <li class=\"nav-item active\"><a class=\"nav-link\" href=\"/\">Home</a></li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"karlDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Category</a>\r\n");
      out.write("                                                <div class=\"dropdown-menu\" aria-labelledby=\"karlDropdown\">\r\n");
      out.write("                                                    ");
for(TopCategory topCategory : topList){ 
      out.write("\r\n");
      out.write("                                                    <a class=\"dropdown-item\" href=\"/\">");
      out.print(topCategory.getName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("                                                                                                        \t\t\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/product/list?subcategory_id=1\">Shopping</a></li>\r\n");
      out.write("                                         \r\n");
      out.write("                                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/cart/list\"><span class=\"karl-level\">3</span>Cart</a></li>\r\n");
      out.write("                                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/cs/qna/list\">Contact</a></li>\r\n");
      out.write("                                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/member/registForm\">SignUp</a></li>\r\n");
      out.write("                                            <li class=\"nav-item\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            \t");
if(session.getAttribute("member")==null){ //세션에 담겨진 데이터가 없다면
      out.write("\r\n");
      out.write("                                            \t\t<a class=\"nav-link\" href=\"/shop/member/loginForm\">SignIn</a>\r\n");
      out.write("                                            \t");
}else{ 
      out.write("\r\n");
      out.write("                                            \t\t<a class=\"nav-link\" href=\"/shop/member/logout\">SignOut</a>\r\n");
      out.write("                                            \t");
} 
      out.write("\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Help Line -->\r\n");
      out.write("                            <div class=\"help-line\">\r\n");
      out.write("                                <a href=\"tel:+346573556778\"><i class=\"ti-headphone-alt\"></i> +34 657 3556 778</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ****** Header Area End ****** -->\r\n");
      out.write("\r\n");
      out.write("        <!-- ****** Top Discount Area Start ****** -->\r\n");
      out.write("        <section class=\"top-discount-area d-md-flex align-items-center\">\r\n");
      out.write("            <!-- Single Discount Area -->\r\n");
      out.write("            <div class=\"single-discount-area\">\r\n");
      out.write("                <h5>Free Shipping &amp; Returns</h5>\r\n");
      out.write("                <h6><a href=\"#\">BUY NOW</a></h6>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Single Discount Area -->\r\n");
      out.write("            <div class=\"single-discount-area\">\r\n");
      out.write("                <h5>20% Discount for all dresses</h5>\r\n");
      out.write("                <h6>USE CODE: Colorlib</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Single Discount Area -->\r\n");
      out.write("            <div class=\"single-discount-area\">\r\n");
      out.write("                <h5>20% Discount for students</h5>\r\n");
      out.write("                <h6>USE CODE: Colorlib</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>");
      out.write("\n");
      out.write("        <!-- ****** Top Discount Area End ****** -->\n");
      out.write("\t\t<div class=\"container\">   \n");
      out.write("\t\t  <form id=\"qnaForm\">\n");
      out.write("\t\t    <input type=\"text\" name=\"title\" placeholder=\"Your name..\">\n");
      out.write("\t\t    <input type=\"text\" name=\"writer\" placeholder=\"Your last name..\">\n");
      out.write("\t\t    <textarea name=\"content\" placeholder=\"Write something..\" style=\"height:200px\"></textarea>\n");
      out.write("\t\t    <input type=\"button\" value=\"Submit\">\n");
      out.write("\t\t  </form>\n");
      out.write("\t</div>\t\n");
      out.write("        <!-- ****** Footer Area Start ****** -->\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<footer class=\"footer_area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Single Footer Area Start -->\r\n");
      out.write("                    <div class=\"col-12 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single_footer_area\">\r\n");
      out.write("                            <div class=\"footer-logo\">\r\n");
      out.write("                                <img src=\"/resources/img/core-img/logo.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"copywrite_text d-flex align-items-center\">\r\n");
      out.write("                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a> &amp; distributed by <a href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Footer Area Start -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-3 col-lg-2\">\r\n");
      out.write("                        <div class=\"single_footer_area\">\r\n");
      out.write("                            <ul class=\"footer_widget_menu\">\r\n");
      out.write("                                <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Faq</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Returns</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Footer Area Start -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-3 col-lg-2\">\r\n");
      out.write("                        <div class=\"single_footer_area\">\r\n");
      out.write("                            <ul class=\"footer_widget_menu\">\r\n");
      out.write("                                <li><a href=\"#\">My Account</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Our Policies</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Afiliates</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Footer Area Start -->\r\n");
      out.write("                    <div class=\"col-12 col-lg-5\">\r\n");
      out.write("                        <div class=\"single_footer_area\">\r\n");
      out.write("                            <div class=\"footer_heading mb-30\">\r\n");
      out.write("                                <h6>Subscribe to our newsletter</h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"subscribtion_form\">\r\n");
      out.write("                                <form action=\"#\" method=\"post\">\r\n");
      out.write("                                    <input type=\"email\" name=\"mail\" class=\"mail\" placeholder=\"Your email here\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"submit\">Subscribe</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"line\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Footer Bottom Area Start -->\r\n");
      out.write("                <div class=\"footer_bottom_area\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"footer_social_area text-center\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\t\t<!-- jQuery (Necessary for All JavaScript Plugins) -->\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t\t<!-- Popper js -->\r\n");
      out.write("\t\t<script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t\t<!-- Bootstrap js -->\r\n");
      out.write("\t\t<script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<!-- Plugins js -->\r\n");
      out.write("\t\t<script src=\"/resources/js/plugins.js\"></script>\r\n");
      out.write("\t\t<!-- Active js -->\r\n");
      out.write("\t\t<script src=\"/resources/js/active.js\"></script>");
      out.write("\n");
      out.write("        <!-- ****** Footer Area End ****** -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.wrapper end -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
