/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 12:45:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.petshop.model.domain.Image;
import com.koreait.petshop.model.domain.SubCategory;
import com.koreait.petshop.model.domain.Color;
import com.koreait.petshop.model.domain.TopCategory;
import com.koreait.petshop.model.domain.Product;
import java.util.List;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/admin/product/../../inc/header.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../../inc/footer.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/admin_navi.jsp", Long.valueOf(1610800158399L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../../shop/shopFooter.jsp", Long.valueOf(1610679240000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.TopCategory");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Color");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Image");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.SubCategory");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	Product product = (Product)request.getAttribute("product");
	List<TopCategory> topList = (List)request.getAttribute("topList");
	List<SubCategory> subList = (List)request.getAttribute("subList");
	SubCategory subCategory = (SubCategory)request.getAttribute("subCategory");
	List<Image>addonList = (List)request.getAttribute("addonList");

      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"Ashion Template\">\n");
      out.write("    <meta name=\"keywords\" content=\"Ashion, unica, creative, html\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Ashion | Petshop</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\"\n");
      out.write("    rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Css Styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/elegant-icons.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("     <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js\"></script>\n");
      out.write("    ");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("* {\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("input[type=text], select, textarea {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tpadding: 12px;\n");
      out.write("\tborder: 1px solid #ccc;\n");
      out.write("\tborder-radius: 4px;\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("\tmargin-top: 6px;\n");
      out.write("\tmargin-bottom: 16px;\n");
      out.write("\tresize: vertical;\n");
      out.write("}\n");
      out.write("input[type=checkbox]{\n");
      out.write("\tpadding-left:50px;\n");
      out.write("}\n");
      out.write("input[type=button] {\n");
      out.write("\tbackground-color: #ca1515;\n");
      out.write("\tcolor: white;\n");
      out.write("\tpadding: 12px 20px;\n");
      out.write("\tborder: none;\n");
      out.write("\tborder-radius: 4px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tmargin : 10px 10px 0px 0px;\n");
      out.write("}\n");
      out.write("input[type=button]:hover {\n");
      out.write("\tbackground-color: #111111;\n");
      out.write("}\n");
      out.write(".container {\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\t//background-color: #f2f2f2;\n");
      out.write("\tpadding: 20px;\n");
      out.write("}\n");
      out.write("#dragArea{\n");
      out.write("\twidth:100%;\n");
      out.write("\theight:180px;\n");
      out.write("\tborder:1px solid #ced4da;\n");
      out.write("\tborder-radius: 5px 5px 5px 5px;\n");
      out.write("\toverflow: auto;\n");
      out.write("}\n");
      out.write(".filebox input[type=\"file\"] { \n");
      out.write("\tposition: absolute; \n");
      out.write("\tpadding: 0; \n");
      out.write("\toverflow: hidden; \n");
      out.write("\tclip:rect(0,0,0,0); \n");
      out.write("\tborder: 0; \n");
      out.write("}\n");
      out.write(".filebox label { \n");
      out.write("\tdisplay: inline-block; \n");
      out.write("\tpadding: .5em .75em; \n");
      out.write("\tbackground-color: #ca1515;\n");
      out.write("\tfont-size: inherit; \n");
      out.write("\tline-height: normal; \n");
      out.write("\tvertical-align: middle; \n");
      out.write("\tcursor: pointer; \n");
      out.write("\tborder: 1px solid #ebebeb; \n");
      out.write("\tborder-bottom-color: #e2e2e2; \n");
      out.write("\tborder-radius: .25em; \n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write(".filebox .upload-name {\n");
      out.write("\theight:38px;\n");
      out.write("\tborder: 1px solid #ebebeb; \n");
      out.write("\tborder-radius: .25em;\n");
      out.write("}\n");
      out.write(".filebox img{\n");
      out.write("\twidth:80px;\n");
      out.write("\theight:80px;\n");
      out.write("}\n");
      out.write(".box{\n");
      out.write("\twidth:100px;\n");
      out.write("\tfloat:left;\n");
      out.write("\tpadding:5px;\n");
      out.write("\tmargin:0px;\n");
      out.write("}\n");
      out.write(".box > img{\n");
      out.write("\twidth:100%; \n");
      out.write("\tmargin: 0px 0px 5px 0px;\n");
      out.write("}\n");
      out.write(".close{\n");
      out.write("\tcolor:red;\n");
      out.write("\tcursor:pointer;\n");
      out.write("}\n");
      out.write(".del{\n");
      out.write("\tcolor:red;\n");
      out.write("\tcursor:pointer;\n");
      out.write("}\n");
      out.write("input[name=color]{\n");
      out.write("\twidth:50px;\n");
      out.write("\theight:30px;\n");
      out.write("\tfont-size:5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("var uploadFiles=[]; //미리보기 이미지 목록 \n");
      out.write("var psize=[]; //유저가 선택한 사이즈를 담는 배열 \n");
      out.write("var color=[]; //유저가 선택한 색상을 담는 배열 \n");
      out.write("//값 불러올때 쓸 변수\n");
      out.write("var id; \n");
      out.write("var name; \n");
      out.write("var thumbnail;\n");
      out.write("var newThum;\n");
      out.write("var oldThum;\n");
      out.write("var sizeArray=[];\n");
      out.write("var colorArray=[];\n");
      out.write("var delAdd=[];\n");
      out.write("var editAdd=[];\n");
      out.write("$(function(){\n");
      out.write("\t\tthumbnail=\"");
      out.print(product.getProduct_id());
      out.write('.');
      out.print(product.getFilename());
      out.write("\";\n");
      out.write("\t\toldThum=\"");
      out.print(product.getFilename());
      out.write("\";\n");
      out.write("\t");

		for(int i=0; i<addonList.size(); i++){
		Image addon=addonList.get(i);
		String fileName =addon.getImage_id()+"."+addon.getFilename();
		int fileId=addon.getImage_id();
	
      out.write("\n");
      out.write("\t\tdelAdd.push(\"");
      out.print(fileName);
      out.write("\");\n");
      out.write("\t\tvar tag=\"<div class=\\\"box\\\" id=\\\"box\\\">\";\n");
      out.write("\t\ttag+=\"<div class=\\\"close\\\" name=\\\"\"+");
      out.print(fileId);
      out.write("+\"\\\" id=\\\"edit\\\">X</div>\";\n");
      out.write("\t\ttag+=\"<img src=\\\"/resources/data/addon/\"+\"");
      out.print(fileName);
      out.write("\"+\"\\\">\";\n");
      out.write("\t\ttag+=\"</div>\";\n");
      out.write("\t\t$(\"#dragArea\").append(tag);\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t\n");
      out.write("\t//셀렉트 박스 변경\n");
      out.write("\t$($(\"select\")[0]).val(");
      out.print(subCategory.getTopcategory_id());
      out.write(").prop(\"selected\", true);\n");
      out.write("\t");
for(int i=0; i< subList.size(); i++){
		SubCategory select= subList.get(i);
	
      out.write("\n");
      out.write("\t\tid=\"");
      out.print(select.getSubcategory_id());
      out.write("\";\n");
      out.write("\t\tname=\"");
      out.print(select.getName());
      out.write("\";\n");
      out.write("\t\t$($(\"select\")[1]).append(\"<option value=\\\"\"+id+\"\\\">\"+name+\"</option>\");\t\n");
      out.write("\t\tconsole.log(\"id = \",id);\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t$($(\"select\")[1]).val(");
      out.print(subCategory.getSubcategory_id());
      out.write(").prop(\"selected\", true);\n");
      out.write("\t\n");
      out.write("\t//사이즈 체크 박스 값 불러오기\n");
      out.write("\t");
for(int i=0; i<product.getPsizeList().size(); i++){
      out.write("\n");
      out.write("\t\tsizeArray[");
      out.print(i);
      out.write(']');
      out.write('=');
      out.write('"');
      out.print(product.getPsizeList().get(i).getPetfit());
      out.write("\";\n");
      out.write("\t");
}
      out.write("\t\n");
      out.write("\tconsole.log(\"arr값 \",sizeArray);\n");
      out.write("\tfor(var i=0; i<$(\"input:checkbox[name='size']\").length; i++){\n");
      out.write("\t\tconsole.log(\"체크박스 값\",$($(\"input:checkbox[name='size']\")[i]).val());\n");
      out.write("\t\t\tswitch(sizeArray[i]){\n");
      out.write("\t\t\t\tcase sizeArray[i]:$(\"input:checkbox[value='\"+sizeArray[i]+\"']\").prop(\"checked\",true);\n");
      out.write("\t\t\t\tbreak;\n");
      out.write("\t\t\t}\n");
      out.write("\t}\n");
      out.write("\tpsizeCheck();//사이즈 값 넣는\n");
      out.write("\t\n");
      out.write("\t//색상 체크박스+텍스트 불러오기\n");
      out.write("\tvar a=");
      out.print(product.getPsizeList().size());
      out.write(';');
      out.write('\n');
      out.write('	');
for(int i=0; i<product.getColorList().size(); i++){
      out.write("\n");
      out.write("\t\tcolorArray[");
      out.print(i);
      out.write(']');
      out.write('=');
      out.write('"');
      out.print(product.getColorList().get(i).getPicker());
      out.write("\";\n");
      out.write("\t");
}
      out.write("\t\n");
      out.write("\tconsole.log(\"colorArray 값 \",colorArray);\n");
      out.write("\tfor(var a=0; a<colorArray.length; a++){\t\n");
      out.write("\t\tswitch(colorArray[a]){\n");
      out.write("\t\t\tcase colorArray[a]:\n");
      out.write("\t\t\t\t$($(\"input:checkbox[name='colorcheck']\")[a]).prop(\"checked\",true);\n");
      out.write("\t\t\t\t$($(\"input:text[name='color']\")[a]).prop(\"value\",colorArray[a]);\n");
      out.write("\t\t\t\tvar c =colorArray[a];\n");
      out.write("\t\t\t\tcolor.push(c);\n");
      out.write("\t\t\t\tbreak;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("$(function(){\n");
      out.write("\t\n");
      out.write("\tCKEDITOR.replace('detail');\t\n");
      out.write("\t\n");
      out.write("\t$($(\"select\")[0]).change(function(){\n");
      out.write("\t\tgetSubList(this);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t/*이미지 드래그*/\n");
      out.write("\t$(\"#dragArea\").on(\"dragenter\", function(e){\n");
      out.write("\t\t$(\"#dragArea\").css(\"border\",\"2px solid blue\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#dragArea\").on(\"dragover\", function(e){ //드래그영역 위에 있는 동안...\n");
      out.write("\t\te.preventDefault();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#dragArea\").on(\"drop\", function(e){ //드래그영역 위에서 이미지를 떨구면..\n");
      out.write("\t\te.preventDefault(); //여타 다른 이벤트를 비활성화시키자...\n");
      out.write("\t\t$(\"#dragArea\").css(\"border\",\"1px solid #ced4da\");\n");
      out.write("\t\t\n");
      out.write("\t\t//자바스크립트로 드래그된 이미지 정보를 구해와서, div영역에 미리보기 효과..\n");
      out.write("\t\tvar fileList = e.originalEvent.dataTransfer.files; //드래그한 파일들에 대한 배열 얻기!!\n");
      out.write("\t\tconsole.log(\"fileList : \",fileList);\n");
      out.write("\t\t\n");
      out.write("\t\t//배열안에 들어있는 이미지들에 대한 미리보기처리...\n");
      out.write("\t\tfor(var i=0;i<fileList.length;i++){\n");
      out.write("\t\t\tuploadFiles.push(fileList[i]); //fileList안의 요소들을 일반배열에 옮겨심기 \n");
      out.write("\t\t\t//왜 심었나? 배열이 지원하는 여러 메서드들을 활용하기 위해...(ex : indexOf..)\n");
      out.write("\t\t\tif(fileList.length==1){\n");
      out.write("\t\t\t\tpreview(fileList[i], i,\"#dragArea\"); //파일 요소 하나를 넘기기\t\t\t\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tpreview(uploadFiles[i], i,\"#dragArea\"); //파일 요소 하나를 넘기기\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#dragArea\").on(\"dragleave\", function(e){ //드래그 영역에서 빠져나가면\n");
      out.write("\t\t$(\"#dragArea\").css(\"border\",\"1px solid #ced4da\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"label\").on(\"mouseover\",function(){\n");
      out.write("\t\t$(\"label\").css(\"background\",\"black\");\n");
      out.write("\t});\n");
      out.write("\t$(\"label\").on(\"mouseout\",function(){\n");
      out.write("\t\t$(\"label\").css(\"background\",\"#ca1515\");\n");
      out.write("\t});\t\n");
      out.write("\t\n");
      out.write("\t//대표 이미지 파일명 출력\n");
      out.write("\tvar fileTarget = $(\".filebox .upload-hidden\"); \n");
      out.write("\tfileTarget.on(\"change\", function(e){ // 값이 변경되면\n");
      out.write("\t\tif(window.FileReader){ // modern browser\n");
      out.write("\t\t\tif($(this)[0].files[0].name!=null){\t\t\t\t\n");
      out.write("\t\t\t\tvar filename = $(this)[0].files[0].name; \n");
      out.write("\t\t\t\tnewThum= $(this)[0].files[0];\n");
      out.write("\t\t\t}\n");
      out.write("\t\t} else { // old IE \n");
      out.write("\t\t\tvar filename = $(this).val().split(\"/\").pop().split(\"\\\\\").pop(); // 파일명만 추출 \n");
      out.write("\t\t\tconsole.log(\"this.val\",$(this)[0].val());\n");
      out.write("\t\t} // 추출한 파일명 삽입 \n");
      out.write("\t\tconsole.log(\"this.files : \"+$(this)[0].files[0].name);\n");
      out.write("\t\t$(this).siblings(\".upload-name\").val(filename); \n");
      out.write("\t\t\n");
      out.write("\t\tpreview(newThum, 1,\".filebox\"); //파일 요소 하나를 넘기기\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#dragArea\").on(\"click\", \".close\", function(e){\n");
      out.write("\t\t//대상 요소 배열에서 삭제\n");
      out.write("\t\t//삭제전에 uploadFiles 라는 배열에 들어있는 file의 index를 구하자!!\n");
      out.write("\t\tvar f = uploadFiles[e.target.id];\n");
      out.write("\t\t\n");
      out.write("\t\tif(e.target.id==\"edit\"){\t\t\t\n");
      out.write("\t\t\talert($(this).attr(\"name\"));\n");
      out.write("\t\t\teditAdd.push($(this).attr(\"name\"));\n");
      out.write("\t\t\tconsole.log(\"수정시 삭제될 이미지 id : \",editAdd);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar index = uploadFiles.indexOf(f); //파일 객체가 몇번째 들어있는지 추출\n");
      out.write("\t\t\n");
      out.write("\t\tuploadFiles.splice(index ,1);\t\n");
      out.write("\t\t//대상 요소 삭제 (시각적으로 삭제) \n");
      out.write("\t\t\n");
      out.write("\t\t$(e.target).parent().remove();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t//사이즈 체크박스 이벤트 구현 \n");
      out.write("\t$(\"input[name='size']\").on(\"click\", function(e){\n");
      out.write("\t\tpsizeCheck();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//컬러 체크박스 이벤트\n");
      out.write("\t$(\"input[name='colorcheck']\").on(\"click\", function(e){\n");
      out.write("\t\tcolorCheck();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("});\n");
      out.write("function psizeCheck(){\n");
      out.write("\tvar ch=$(\"input[name='size']\");\n");
      out.write("\tvar len =$(ch).length; //반복문이용하려고..\n");
      out.write("\t\n");
      out.write("\tpsize=[];//배열 초기화\n");
      out.write("\tconsole.log(\"채우기 전 psize의 길이는 \",psize.length);\n");
      out.write("\t\n");
      out.write("\tfor(var i=0;i<len;i++){\n");
      out.write("\t\t//만일 체크가 되어있다면, 기존 배열을 모두 지우고, 체크된 체크박스 값만 배열에 넣자!!\n");
      out.write("\t\tif($($(ch)[i]).is(\":checked\")){\n");
      out.write("\t\t\tpsize.push($($(ch)[i]).val());\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.log(i,\"번째 체크박스 상태는 \", $($(ch)[i]).is(\":checked\"));\n");
      out.write("\t}\t\t\n");
      out.write("\tconsole.log(\"psize의 길이는 \",psize.length);\n");
      out.write("\tconsole.log(\"서버에 전송할 사이즈 배열의 구성은 \", psize);\n");
      out.write("}\n");
      out.write("function colorCheck(){\n");
      out.write("\tvar ch=$(\"input[name='colorcheck']\");\n");
      out.write("\tvar len =$(ch).length; //반복문이용하려고..\n");
      out.write("\tcolor=[];//배열 초기화\n");
      out.write("\t\n");
      out.write("\tfor(var i=0;i<len;i++){\n");
      out.write("\t\t//만일 체크가 되어있다면, 기존 배열을 모두 지우고, 체크된 체크박스 값만 배열에 넣자!!\n");
      out.write("\t\tif($($(ch)[i]).is(\":checked\")){\t\t\n");
      out.write("\t\t\tconsole.log($($(\"input[name='color']\")[i]).val());\t\t\n");
      out.write("\t\t\tcolor.push($($(\"input[name='color']\")[i]).val());\n");
      out.write("\t\t}\n");
      out.write("\t}\t\t\n");
      out.write("\tconsole.log(\"서버에 전송할 컬러 배열의 구성은 \", color);\n");
      out.write("}\n");
      out.write("function getSubList(obj){\n");
      out.write("\t//alert($(obj).val());\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/admin/product/sublist\",\n");
      out.write("\t\ttype:\"get\",\n");
      out.write("\t\tdata:{\n");
      out.write("\t\t\ttopcategory_id:$(obj).val()\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess:function(result){\n");
      out.write("\t\t\t//alert(\"서버로 받은 결과 \"+result[0].topcategory_id);\n");
      out.write("\t\t\t$($(\"select\")[1]).empty();\n");
      out.write("\t\t\t$($(\"select\")[1]).append(\"<option>하위 카테고리</option>\")\n");
      out.write("\t\t\tfor(var i=0; i<result.length; i++){\n");
      out.write("\t\t\t\tvar subCategory = result[i];\n");
      out.write("\t\t\t\t$($(\"select\")[1]).append(\"<option value=\\\"\"+subCategory.subcategory_id+\"\\\">\"+subCategory.name+\"</option>\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("//업로드 이미지 미리보기\n");
      out.write("function preview(file, index, c){\n");
      out.write("\t//js로 이미지 미리보기를 구현하려면, 파일리더를 이용하면 된다 FileReader\n");
      out.write("\tvar reader = new FileReader(); //아직은 읽을 대상 파일이 결정되지 않음..\n");
      out.write("\t//파일일 읽어들이면, 이벤트 발생시킴 \n");
      out.write("\treader.onload=function(e){\n");
      out.write("\t\t//console.log(e.currentTarget.size);\n");
      out.write("\t\t\n");
      out.write("\t\tif(c==\"#dragArea\"){\t\t\t\n");
      out.write("\t\t\tvar tag=\"<div class=\\\"box\\\" id=\\\"box\\\">\";\n");
      out.write("\t\t\ttag+=\"<div class=\\\"close\\\" id=\\\"\"+index+\"\\\">X</div>\";\n");
      out.write("\t\t\ttag+=\"<img src=\\\"\"+e.currentTarget.result+\"\\\">\";\n");
      out.write("\t\t\ttag+=\"</div>\";\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tif($(\"input[type='file']\").val()!=null){\t\t\t\t\n");
      out.write("\t\t\t\t$(\"img\").remove(\"#mainImage\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tvar tag=\"<img id='mainImage' src=\\\"\"+e.currentTarget.result+\"\\\">\";\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$(c).append(tag);\n");
      out.write("\t\t\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\treader.readAsDataURL(file); //지정한 파일을 읽는다(매개변수로는 파일이 와야함)\n");
      out.write("}\n");
      out.write("function edit(){\n");
      out.write("\tif(confirm(\"수정하시겠습니까?\")){\n");
      out.write("\t\tvar formData = new FormData(document.getElementById('data'));\n");
      out.write("\t\t\n");
      out.write("\t\tif(newThum!=null){\t\t\n");
      out.write("\t\t\tformData.append(\"repImg\",newThum);\t//새로 저장될 썸네일\n");
      out.write("\t\t\tformData.append(\"delRep\", thumbnail);\n");
      out.write("\t\t\tconsole.log(\"repImg : \",newThum.name);\n");
      out.write("\t\t\tconsole.log(\"delRep : \",thumbnail);\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tformData.append(\"filename\",oldThum);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$.each(uploadFiles, function( i, file){\n");
      out.write("\t\t\tformData.append(\"addImg\", file,  file.name); // <input type=\"file\" name=\"addImg> 동일한 효과 \n");
      out.write("\t\t\tconsole.log(\"수정시 등록될 이미지 : \",file.name);\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write(" \t\tfor(var i=0; i<editAdd.length; i++){\n");
      out.write("\t\t\tformData.append(\"editAdd[\"+i+\"]\", editAdd[i]);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfor(var i=0;i<psize.length;i++){\n");
      out.write("\t\t\tformData.append(\"psize[\"+i+\"].petfit\", psize[i]);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t//색상 체크가 되어있으면 값을 불러와서 바꾸기\n");
      out.write("\t\tcolorCheck();\n");
      out.write("\t\tfor(var i=0;i<color.length;i++){\n");
      out.write("\t\t\tformData.append(\"colors[\"+i+\"].picker\", color[i]);\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.log(\"탑카테고리 id : \",$($(\"select\")[0]).val());\n");
      out.write("\t\tconsole.log(\"서브카테고리 id : \",$($(\"select\")[1]).val());\t\t\n");
      out.write("\t\tconsole.log(\"상품이름 : \",$('form [name=\"product_name\"]').val());\n");
      out.write("\t\tconsole.log(\"가격 : \",$('form [name=\"price\"]').val());\n");
      out.write("\t\tconsole.log(\"상세설명 : \",$('form [name=\"detail\"]').val());\n");
      out.write("\t\tconsole.log(\"formData : \",formData);\n");
      out.write("\t\tconsole.log(\"color : \",color);\n");
      out.write("\t\tconsole.log(\"psize : \",psize);\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"/async/admin/product/update\",\n");
      out.write("\t\t\tdata:formData,\n");
      out.write("\t\t\tcontentType:false,\n");
      out.write("\t\t\tprocessData:false,\n");
      out.write("\t\t\ttype:\"post\",\n");
      out.write("\t\t\tsuccess:function(responseData){\n");
      out.write("\t\t\t\tif(responseData.resultCode==1){\n");
      out.write("\t\t\t\t\talert(responseData.msg);\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\talert(responseData.msg);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function del(){\n");
      out.write("\tif(confirm(\"삭제하시겠습니까?\")){\n");
      out.write("\t\tvar formData = new FormData(document.getElementById('data'));\n");
      out.write("\t\t\n");
      out.write("\t\tformData.append(\"delRep\", thumbnail);\n");
      out.write("\t\t\n");
      out.write("\t\tfor(var i=0; i<delAdd.length; i++){\n");
      out.write("\t\t\tformData.append(\"delAdd[\"+i+\"]\", delAdd[i]);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"/async/admin/product/del\",\n");
      out.write("\t\t\t\tdata:formData,\n");
      out.write("\t\t\t\tcontentType:false,\n");
      out.write("\t\t\t\tprocessData:false,\n");
      out.write("\t\t\t\ttype:\"post\",\n");
      out.write("\t\t\t\tsuccess:function(responseData){\n");
      out.write("\t\t\t\t\tif(responseData.resultCode==1){\n");
      out.write("\t\t\t\t\t\talert(responseData.msg);\n");
      out.write("\t\t\t\t\t\tlocation.href=responseData.url;\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\talert(responseData.msg);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" \n");
      out.write("<!-- Page Preloder -->\n");
      out.write("    <div id=\"preloder\">\n");
      out.write("        <div class=\"loader\"></div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write(" <!-- Offcanvas Menu Begin -->\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\n");
      out.write("        <div class=\"offcanvas__close\">+</div>\n");
      out.write("        <ul class=\"offcanvas__widget\">\n");
      out.write("            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"offcanvas__logo\">\n");
      out.write("            <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\n");
      out.write("        <div class=\"offcanvas__auth\">\n");
      out.write("            <a href=\"#\">Login</a>\n");
      out.write("            <a href=\"#\">Register</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Offcanvas Menu End -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-3 col-lg-2\">\n");
      out.write("                    <div class=\"header__logo\">\n");
      out.write("                        <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xl-6 col-lg-7\">\n");
      out.write("                    <nav class=\"header__menu\">\n");
      out.write("                        <ul>\t\n");
      out.write("                        \t<li></li>\n");
      out.write("                            <li class=\"active\"><a href=\"/admin\">Home</a></li>\n");
      out.write("                            <li><a href=\"#\">상품</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/admin/product/list\">목록</a></li>\n");
      out.write("                                    <li><a href=\"/admin/product/registform\">등록</a></li>\n");
      out.write("                                     <li><a href=\"#\">수정</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"#\">회원</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=/admin/member/list>목록</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"#\">결제</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"#\">목록</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            \n");
      out.write("                            <li><a href=\"./blog.html\">Blog</a></li>\n");
      out.write("                            <li><a href=\"/admin/contact\">Contact</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3\">\n");
      out.write("                    <div class=\"header__right\">\n");
      out.write("                        <div class=\"header__right__auth\">\n");
      out.write("                        \t<a href=\"/\">Shop Main</a>\n");
      out.write("                      \t\t<a href=\"#\">Login</a>\n");
      out.write("                            <a href=\"#\">Logout</a>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"canvas__open\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Section End -->");
      out.write("\n");
      out.write("\t<section class=\"product spad\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t<h4>상품 상세보기</h4>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<form id=\"data\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_id\" value=\"");
      out.print(product.getProduct_id());
      out.write("\"/>\t\t\n");
      out.write("\t\t\t\t<select name=\"topcategory_id\">\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(topList.size()+1);
      out.write("\">상위 카테고리</option>\n");
      out.write("\t\t\t\t\t");
for(TopCategory topCategory : topList){ 
      out.write("\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(topCategory.getTopcategory_id());
      out.write('"');
      out.write('>');
      out.print(topCategory.getName() );
      out.write("</option>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<select name=\"subCategory.subcategory_id\">\n");
      out.write("\t\t\t\t\t<option>하위 카테고리</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"product_name\" value=\"");
      out.print(product.getProduct_name());
      out.write("\"> \n");
      out.write("\t\t\t\t<input type=\"text\" name=\"price\" value=\"");
      out.print(product.getPrice());
      out.write("\"> \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"filebox\"> \n");
      out.write("\t\t\t\t\t<input class=\"upload-name\" value=\"파일이름\" disabled=\"disabled\"> \n");
      out.write("\t\t\t\t\t<label for=\"ex_filename\">업로드</label> \n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"ex_filename\" class=\"upload-hidden\" name=\"repImg\"> \n");
      out.write("\t\t\t\t\t<img id=\"mainImage\" src=\"/resources/data/basic/");
      out.print(product.getProduct_id());
      out.write('.');
      out.print(product.getFilename());
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t등록할 이미지를 드래그 해주세요.\n");
      out.write("\t\t\t\t<div id=\"dragArea\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\tXS<input type=\"checkbox\" name=\"size\" value=\"XS\">\n");
      out.write("\t\t\t\t\tS<input type=\"checkbox\" name=\"size\" value=\"S\">\n");
      out.write("\t\t\t\t\tM<input type=\"checkbox\" name=\"size\" value=\"M\">\n");
      out.write("\t\t\t\t\tL<input type=\"checkbox\" name=\"size\" value=\"L\">\n");
      out.write("\t\t\t\t\tXL<input type=\"checkbox\" name=\"size\" value=\"XL\">\n");
      out.write("\t\t\t\t\tXXL<input type=\"checkbox\" name=\"size\" value=\"XXL\">\n");
      out.write("\t\t\t\t\t<p>*등록할 사이즈를 선택해주세요.</p>\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\t\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\t\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\t\t\t\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" \tname=\"colorcheck\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"color\" placeholder=\"색상 적는 곳\">\n");
      out.write("\t\t\t\t\t<p>*원하는 색상을 적고 체크해주세요</p>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<textarea name=\"detail\">");
      out.print(product.getDetail() );
      out.write("</textarea>\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수정\" onClick=\"edit()\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"삭제\" onClick=\"del()\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"목록으로\" onClick=\"location.href='/admin/product/list'\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("<!-- Footer Section Begin -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-7\">\n");
      out.write("                <div class=\"footer__about\">\n");
      out.write("                    <div class=\"footer__logo\">\n");
      out.write("                        <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt\n");
      out.write("                    cilisis.</p>\n");
      out.write("                    <div class=\"footer__payment\">\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-1.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-2.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-3.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-4.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-5.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-5\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Quick links</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">About</a></li>\n");
      out.write("                        <li><a href=\"#\">Blogs</a></li>\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-4\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Account</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">My Account</a></li>\n");
      out.write("                        <li><a href=\"#\">Orders Tracking</a></li>\n");
      out.write("                        <li><a href=\"#\">Checkout</a></li>\n");
      out.write("                        <li><a href=\"#\">Wishlist</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-4 col-md-8 col-sm-8\">\n");
      out.write("                <div class=\"footer__newslatter\">\n");
      out.write("                    <h6>NEWSLETTER</h6>\n");
      out.write("                    <form action=\"#\">\n");
      out.write("                        <input type=\"text\" placeholder=\"Email\">\n");
      out.write("                        <button type=\"submit\" class=\"site-btn\">Subscribe</button>\n");
      out.write("                    </form>\n");
      out.write("                    <div class=\"footer__social\">\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-youtube-play\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                <div class=\"footer__copyright__text\">\n");
      out.write("                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a></p>\n");
      out.write("                </div>\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("<!-- Footer Section End -->\n");
      out.write("\n");
      out.write("<!-- Search Begin -->\n");
      out.write("<div class=\"search-model\">\n");
      out.write("    <div class=\"h-100 d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"search-close-switch\">+</div>\n");
      out.write("        <form class=\"search-model-form\">\n");
      out.write("            <input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Search End -->");
      out.write('\n');
      out.write("\n");
      out.write("<!-- Js Plugins -->\n");
      out.write("<script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/mixitup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.countdown.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.slicknav.js\"></script>\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.nicescroll.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
