/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-15 04:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.petshop.model.common.Formatter;
import com.koreait.petshop.model.domain.Cart;
import com.koreait.petshop.model.domain.Paymethod;
import java.util.List;
import com.koreait.petshop.model.domain.Member;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/shop/payment/./../../inc/footer.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/payment/./../../inc/header.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/payment/./../../inc/shop_navi.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/payment/../shopFooter.jsp", Long.valueOf(1610679240000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.koreait.petshop.model.common.Formatter");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Member");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Paymethod");
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	List<Cart> cartList=(List)request.getAttribute("cartList");
	List<Paymethod> paymethodList = (List)request.getAttribute("paymethodList");
	Member member=(Member)session.getAttribute("member");
	
	//장바구니로부터 , 상품 가액 계산 
	int totalPrice=0;
	for(Cart cart:cartList){
		totalPrice +=(cart.getQuantity() * cart.getPrice());
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"Ashion Template\">\n");
      out.write("    <meta name=\"keywords\" content=\"Ashion, unica, creative, html\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Ashion | Petshop</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\"\n");
      out.write("    rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Css Styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/elegant-icons.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("     <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js\"></script>\n");
      out.write("    ");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tfunction setData(ch){\n");
      out.write("\t\tvar form=document.querySelector(\"#checkout__form\");\n");
      out.write("\t\tif(ch.checked){ //체크했다면, 주문자 정보를 받는자 정보에 대입하자 \n");
      out.write("\t\t\tform.receiver_name.value=form.member_name.value;\n");
      out.write("\t\t\tform.receiver_phone.value=form.member_phone.value;\n");
      out.write("\t\t\tform.receiver_addr.value=form.member_addr.value;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t//받는 사람 정보를 다시 원상 복구(초기화)\n");
      out.write("\t\t\tform.receiver_name.value=\"\";\n");
      out.write("\t\t\tform.receiver_phone.value=\"\";\n");
      out.write("\t\t\tform.receiver_addr.value=\"\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction order(){\n");
      out.write("\t\t$(\"#checkout__form\").attr({\n");
      out.write("\t\t\taction:\"/shop/payment/confirm\",\n");
      out.write("\t\t\tmethod:\"post\"\n");
      out.write("\t\t});\n");
      out.write("\t\t$(\"#checkout__form\").submit();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  \n");
      out.write("    <!-- Offcanvas Menu Begin -->\n");
      out.write("    \n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\n");
      out.write("        <div class=\"offcanvas__close\">+</div>\n");
      out.write("        <ul class=\"offcanvas__widget\">\n");
      out.write("            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"offcanvas__logo\">\n");
      out.write("            <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\n");
      out.write("        <div class=\"offcanvas__auth\">\n");
      out.write("            <a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("            <a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Offcanvas Menu End -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("  ");
      out.write("\n");
      out.write("<!-- Page Preloder -->\n");
      out.write("\n");
      out.write(" <!-- Offcanvas Menu Begin -->\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\n");
      out.write("        <div class=\"offcanvas__close\">+</div>\n");
      out.write("        <ul class=\"offcanvas__widget\">\n");
      out.write("            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("            <li><a href=\"/shop/cart/list\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"offcanvas__logo\">\n");
      out.write("            <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\n");
      out.write("        <div class=\"offcanvas__auth\">\n");
      out.write("            <a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("            <a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Offcanvas Menu End -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-3 col-lg-2\">\n");
      out.write("                    <div class=\"header__logo\">\n");
      out.write("                        <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xl-6 col-lg-7\">\n");
      out.write("                    <nav class=\"header__menu\">\n");
      out.write("                        <ul>\n");
      out.write("                        \t<li></li>\n");
      out.write("                            <li class=\"active\"><a href=\"/\">Home</a></li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">옷</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=1\">패딩</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=2\">나시</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=3\">점프수트</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=4\">원피스</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">사료</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=5\">연어</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=6\">소고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=7\">양고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=8\">닭고기</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">간식</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=9\">츄잉껌</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=10\">츄르</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=11\">소시지</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=12\">육포말이</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">악세서리</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=13\">모자</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=14\">목걸이</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=15\">펫스텝</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=16\">철망</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <!-- <li><a href=\"/\">Shop</a></li> -->\n");
      out.write("                            <li><a href=\"/shop/cart/list\">Cart</a>\n");
      out.write("                               <!--  <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"./product-details.html\">Product Details</a></li>\n");
      out.write("                                     <li><a href=\"/shop/cart/list\">Cart</a></li>\n");
      out.write("                                    <li><a href=\"./checkout.html\">Checkout</a></li>\n");
      out.write("                                    <li><a href=\"./blog-details.html\">Blog Details</a></li>\n");
      out.write("                            <li><a href=\"./blog.html\">Blog</a></li>\n");
      out.write("                            <li><a href=\"./contact.html\">Contact</a></li>\n");
      out.write("                                </ul> -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"col-lg-3\">\n");
      out.write("                    <div class=\"header__right\">\n");
      out.write("                        <div class=\"header__right__auth\">\n");
      out.write("                            ");
if(session.getAttribute("member")==null){ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("                            \t<a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("            \t\t\t\t");
}else{ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/logout\">LogOut</a>\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/mypage_order\">MyPage</a>\n");
      out.write("        \t\t\t\t\t");
} 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <ul class=\"header__right__widget\">\n");
      out.write("                            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"canvas__open\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Section End -->");
      out.write("\n");
      out.write("    <!-- Header Section End -->\n");
      out.write("\n");
      out.write("    <!-- Breadcrumb Begin -->\n");
      out.write("    <div class=\"breadcrumb-option\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"breadcrumb__links\">\n");
      out.write("                        <a href=\"../../\"><i class=\"fa fa-home\"></i> Home</a>\n");
      out.write("                        <span>Customer Information</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Breadcrumb End -->\n");
      out.write("\n");
      out.write("    <!-- Checkout Section Begin -->\n");
      out.write("    <section class=\"checkout spad\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <h6 class=\"coupon__link\"><span class=\"icon_tag_alt\"></span> <a href=\"/shop/cart/list\">카트로 돌아가기</a> Click\n");
      out.write("                    </h6>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <form id=\"checkout__form\" action=\"#\" class=\"checkout__form\">\n");
      out.write("            \t<input type=\"hidden\" name=\"total_price\" value=\"");
      out.print(totalPrice);
      out.write("\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-8\">\n");
      out.write("                        <h5>주문자정보</h5>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("\t                            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>고객명<span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" class=\"form-control\" id=\"member_name\" value=\"");
      out.print(member.getName() );
      out.write("\" required>\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>\n");
      out.write("\t                            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>연락처<span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" class=\"form-control\"  id=member_phone value=\"");
      out.print(member.getPhone());
      out.write("\">\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>\n");
      out.write("\t                            <div class=\"col-lg-12\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>주소 <span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" class=\"form-control\"  id=\"member_addr\" value=\"");
      out.print(member.getAddr());
      out.write("\">\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>    \n");
      out.write("\t                            <!-- 중간 체크박스  -->\n");
      out.write("\t                           \t<div class=\"col-12 mb-3\">\n");
      out.write("\t                                  <div class=\"custom-control custom-checkbox d-block mb-2\">\n");
      out.write("\t                                          <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck1\" onClick=\"setData(this)\">\n");
      out.write("\t                                          <label class=\"custom-control-label\" for=\"customCheck1\">주문자와 동일</label>\n");
      out.write("\t                                  </div>\n");
      out.write("\t                            </div> \n");
      out.write("\t                            <!-- 받는분 -->\n");
      out.write("\t                            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>받는분 성함<span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" class=\"form-control\" name=\"receiver_name\" value=\"\" required>\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>\n");
      out.write("\t                            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>받는분 연락처<span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" name=\"receiver_phone\" required>\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>\n");
      out.write("\t                            <div class=\"col-lg-12\">\n");
      out.write("\t                                <div class=\"checkout__form__input\">\n");
      out.write("\t                                    <p>받는분 주소 <span>*</span></p>\n");
      out.write("\t                                    <input type=\"text\" name=\"receiver_addr\">\n");
      out.write("\t                                </div>\n");
      out.write("\t                            </div>    \n");
      out.write("                               \n");
      out.write("                                \n");
      out.write("                       \n");
      out.write("                             </div>\n");
      out.write("                          </div>\n");
      out.write("                         \t  <!-- 장바구니목록  -->\n");
      out.write("                        <div class=\"col-lg-4\">\n");
      out.write("                            <div class=\"checkout__order\">\n");
      out.write("                                <h5>장바구니 목록</h5>\n");
      out.write("                                <div class=\"checkout__order__product\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li>\n");
      out.write("                                            <span style=\"display:inline-block; width:130px\" class=\"top__text\" >상품명</span>\n");
      out.write("                                            \n");
      out.write("                                            <span class=\"top__text__right\">금액</span>                                  \n");
      out.write("                                        </li>\n");
      out.write("                                        ");
int sum=0; 
      out.write("\n");
      out.write("                                        ");
for(Cart cart:cartList){
      out.write("\n");
      out.write("                                        <li>");
      out.print(cart.getProduct_name());
      out.write("\n");
      out.write("                                        \t<span>");
      out.print(cart.getPrice());
      out.write("</span>\n");
      out.write("                                       \t</li>\n");
      out.write("\t                                       \t");

												sum= sum + (cart.getPrice()*cart.getQuantity());
											
      out.write("\n");
      out.write("                          \t\t\t\t");
}
      out.write("\n");
      out.write("                                        \n");
      out.write("                                    </ul>\n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"checkout__order__total\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        \n");
      out.write("                                        <li>Total <span>");
      out.print(Formatter.getCurrency(sum) );
      out.write("</span></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"checkout__order__widget\">\n");
      out.write("                                \n");
      out.write("                            \n");
      out.write("                                <!--결제방법선택-->\n");
      out.write("                                \n");
      out.write("                                <div class=\"checkout__order__total\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li>결제방법</li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                                    <div class=\"col-12 mb-3\">\n");
      out.write("                                        <select class=\"custom-select d-block w-100\" id=\"country\" name=\"paymethod_id\">\n");
      out.write("                                        \n");
      out.write("                                        ");
for(Paymethod paymethod : paymethodList){ 
      out.write("       \n");
      out.write("                                        <option value=\"");
      out.print(paymethod.getPaymethod_id());
      out.write('"');
      out.write('>');
      out.print(paymethod.getMethod() );
      out.write("</option>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                    </div> \n");
      out.write("                                \n");
      out.write("                                </div>\n");
      out.write("                                <a href=\"javascript:order()\"class=\"site-btn\">결제하기</a>                          \t\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                     </div>          \n");
      out.write("                </form>  \n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Checkout Section End -->\n");
      out.write("\n");
      out.write("        <!-- Instagram Begin -->\n");
      out.write("        <div class=\"instagram\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-1.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-2.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-3.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-4.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-5.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-4 col-sm-4 p-0\">\n");
      out.write("                        <div class=\"instagram__item set-bg\" data-setbg=\"/resources/img/instagram/insta-6.jpg\">\n");
      out.write("                            <div class=\"instagram__text\">\n");
      out.write("                                <i class=\"fa fa-instagram\"></i>\n");
      out.write("                                <a href=\"#\">@ ashion_shop</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Instagram End -->\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("<!-- Footer Section Begin -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-7\">\n");
      out.write("                <div class=\"footer__about\">\n");
      out.write("                    <div class=\"footer__logo\">\n");
      out.write("                        <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt\n");
      out.write("                    cilisis.</p>\n");
      out.write("                    <div class=\"footer__payment\">\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-1.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-2.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-3.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-4.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-5.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-5\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Quick links</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">About</a></li>\n");
      out.write("                        <li><a href=\"#\">Blogs</a></li>\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-4\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Account</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">My Account</a></li>\n");
      out.write("                        <li><a href=\"#\">Orders Tracking</a></li>\n");
      out.write("                        <li><a href=\"#\">Checkout</a></li>\n");
      out.write("                        <li><a href=\"#\">Wishlist</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-4 col-md-8 col-sm-8\">\n");
      out.write("                <div class=\"footer__newslatter\">\n");
      out.write("                    <h6>NEWSLETTER</h6>\n");
      out.write("                    <form action=\"#\">\n");
      out.write("                        <input type=\"text\" placeholder=\"Email\">\n");
      out.write("                        <button type=\"submit\" class=\"site-btn\">Subscribe</button>\n");
      out.write("                    </form>\n");
      out.write("                    <div class=\"footer__social\">\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-youtube-play\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                <div class=\"footer__copyright__text\">\n");
      out.write("                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a></p>\n");
      out.write("                </div>\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("<!-- Footer Section End -->\n");
      out.write("\n");
      out.write("<!-- Search Begin -->\n");
      out.write("<div class=\"search-model\">\n");
      out.write("    <div class=\"h-100 d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"search-close-switch\">+</div>\n");
      out.write("        <form class=\"search-model-form\">\n");
      out.write("            <input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Search End -->");
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("<!-- Js Plugins -->\n");
      out.write("<script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/mixitup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.countdown.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.slicknav.js\"></script>\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.nicescroll.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
