/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 12:41:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.petshop.model.domain.Member;

public final class mypage_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/shop/member/./../../inc/shop_navi.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/member/./../../inc/header.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/member/../shopFooter.jsp", Long.valueOf(1610679240000L));
    _jspx_dependants.put("/WEB-INF/views/shop/member/./../../inc/footer.jsp", Long.valueOf(1610679240000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.koreait.petshop.model.domain.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	Member member = (Member)request.getSession().getAttribute("member");	

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  ");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"Ashion Template\">\n");
      out.write("    <meta name=\"keywords\" content=\"Ashion, unica, creative, html\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Ashion | Petshop</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\"\n");
      out.write("    rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Css Styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/elegant-icons.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/jquery-ui.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" type=\"text/css\">\n");
      out.write("    \n");
      out.write("     <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js\"></script>\n");
      out.write("    ");
      out.write("\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/signup_style.css\" type=\"text/css\">\n");
      out.write("<style >\n");
      out.write("/* 컨테이너 영역 padding */\n");
      out.write(".container {\n");
      out.write("  padding: 16px;\n");
      out.write("  background-color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 내용 영역 너비 조정 영역*/\n");
      out.write("input[type=text], input[type=password] , .address_button{\n");
      out.write("  width: 99%;\n");
      out.write("  padding: 15px;\n");
      out.write("  margin: 5px 0 22px 0;\n");
      out.write("  display: inline-block;\n");
      out.write("  border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("select {\n");
      out.write("   width: 100%;\n");
      out.write("   padding: 15px;\n");
      out.write("    margin: 5px 0 22px 0;\n");
      out.write("    display: inline;\n");
      out.write("     border: 1px solid #e1e1e1;\n");
      out.write("     font-size: 14px;\n");
      out.write("     color: #666666;\n");
      out.write("     border-radius: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=text]:focus, input[type=password]:focus ,select:focus , .address_button:focus{\n");
      out.write("  background-color: #ddd;\n");
      out.write("  outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".site-btn:hover {\n");
      out.write("  background-color: #ddd;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 로딩 바 스타일 영역 */\n");
      out.write(".loader {\n");
      out.write("   width: 40px;\n");
      out.write("   height: 40px;\n");
      out.write("   position: absolute;\n");
      out.write("   top: 55%;\n");
      out.write("   left: 50%;\n");
      out.write("   margin-top: -13px;\n");
      out.write("   margin-left: -13px;\n");
      out.write("   border-radius: 60px;\n");
      out.write("    animation: loader 0.8s linear infinite; \n");
      out.write("   -webkit-animation: loader 0.8s linear infinite;    \n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 사용가능한 경우*/\n");
      out.write(".id_available, .pwdck_1{\n");
      out.write("      color : blue;\n");
      out.write("      display : none;\n");
      out.write("   }\n");
      out.write("\n");
      out.write("/* 사용불가능한 경우 */\n");
      out.write(".id_unavailable, .pwdck_2{\n");
      out.write("   color : red;\n");
      out.write("   display : none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 유효성 체크 */\n");
      out.write(".final_user_id_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("} \n");
      out.write("\n");
      out.write(".final_name_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("} \n");
      out.write("\n");
      out.write(".final_password_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write(".final_pwdck_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("} \n");
      out.write(".final_email_id_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write(".final_email_server_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write(".final_phone_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write(".final_zipcode_ck{\n");
      out.write("color : red;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write(".final_addr_ck{\n");
      out.write("   color : red;\n");
      out.write("   display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(function(){\t\n");
      out.write("\t/* 비밀번호 확인 */\n");
      out.write("\t$('.pwdCheck').on(\"propertychange change keyup paste input\", function(){\n");
      out.write("\t\tvar pwd = $('.password').val();\n");
      out.write("\t\tvar pwdck = $('.pwdCheck').val();\n");
      out.write("\t\t$('.final_pwck_ck').css('display', 'none');\n");
      out.write("\t    \n");
      out.write("\t\tif(pwd == pwdck){\n");
      out.write("\t    \t$('.pwdck_1').css(\"display\",\"inline-block\");\n");
      out.write("\t\t\t$('.pwdck_2').css(\"display\", \"none\");\t\t\n");
      out.write("\t\t\tpwd_pwdckCheck = true;\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$('.pwdck_2').css(\"display\",\"inline-block\");\n");
      out.write("\t\t\t\t$('.pwdck_1').css(\"display\", \"none\");\t\n");
      out.write("\t\t\t\tpwd_pwdckCheck = false;\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\n");
      out.write("\t/* 유효성 검사 통과유무 변수*/\n");
      out.write("\tvar pwdCheck = false;\n");
      out.write("\tvar pwdckCheck = false;\n");
      out.write("\tvar pwd_pwdckCheck = false;\n");
      out.write("\tvar mailIdCheck = false;\n");
      out.write("\tvar mailServerCheck = false;\n");
      out.write("\tvar phoneCheck = false;\n");
      out.write("\tvar zipcodeCheck = false;\n");
      out.write("\tvar addrCheck = false;\t \n");
      out.write("\t\n");
      out.write("\t//회원정보 수정처리\n");
      out.write("\t$(\"#edit\").click(function(){\n");
      out.write("\t\tvar user_id = $('.user_id').val();\n");
      out.write("\t\tvar name = $('.name').val();\n");
      out.write("\t\tvar password = $('.password').val();\n");
      out.write("\t\tvar pwdCheck = $('.pwdCheck').val();\n");
      out.write("\t\tvar email_id = $('.email_id').val();\n");
      out.write("\t\tvar email_server = $('.email_server').val();\n");
      out.write("\t\tvar phone = $('.phone').val();\n");
      out.write("\t\tvar zipcode = $('.zipcode').val();\n");
      out.write("\t\tvar addr = $('.addr_2').val();\n");
      out.write("\t\t\t\n");
      out.write("\t\t/* 비밀번호 유효성 확인 */\n");
      out.write("\t\tif(password == \"\"){\n");
      out.write("\t\t\t$('.final_password_ck').css('display', 'inline');\n");
      out.write("\t\t\tpwdCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_password_ck').css('display', 'none');\n");
      out.write("\t\t\tpwdCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 비밀번호 재입력 유효성 확인 */\n");
      out.write("\t\tif(pwdCheck  == \"\"){\n");
      out.write("\t\t\t$('.pwdck_2').css('display', 'inline');\n");
      out.write("\t\t\tpwdckCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.pwdck_2').css('display', 'none');\n");
      out.write("\t\t\tpwdckCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 이메일 id 유효성 검사 */\n");
      out.write("\t\tif(email_id  == \"\"){\n");
      out.write("\t\t\t$('.final_email_id_ck').css('display', 'inline');\n");
      out.write("\t\t\tmailIdCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_email_id_ck').css('display', 'none');\n");
      out.write("\t\t\tmailIdCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 이메일 server 유효성 검사 */\n");
      out.write("\t\tif(email_server  == null){\n");
      out.write("\t\t\t$('.final_email_server_ck').css('display', 'inline');\n");
      out.write("\t\t\tmailServerCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_email_server_ck').css('display', 'none');\n");
      out.write("\t\t\tmailServerCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 핸드폰 유효성 검사 */\n");
      out.write("\t\tif(phone  == \"\"){\n");
      out.write("\t\t\t$('.final_phone_ck').css('display', 'inline');\n");
      out.write("\t\t\tphoneCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_phone_ck').css('display', 'none');\n");
      out.write("\t\t\tphoneCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 우편번호 유효성 검사 */\n");
      out.write("\t\tif(zipcode  == \"\"){\n");
      out.write("\t\t\t$('.final_zipcode_ck').css('display', 'inline');\n");
      out.write("\t\t\tzipcodeCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_zipcode_ck').css('display', 'none');\n");
      out.write("\t\t\tzipcodeCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* 주소 유효성 검사 */\n");
      out.write("\t\tif(addr  == \"\"){\n");
      out.write("\t\t\t$('.final_addr_ck').css('display', 'inline');\n");
      out.write("\t\t\taddrCheck = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('.final_addr_ck').css('display', 'none');\n");
      out.write("\t\t\taddrCheck = true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t if(pwdCheck &&pwdCheck &&pwd_pwdckCheck &&mailIdCheck &&mailServerCheck &&phoneCheck && zipcodeCheck &&addrCheck){\n");
      out.write("\t\t\t//회원등록\n");
      out.write("\t\t\tedit();\n");
      out.write("\t     }  \t\n");
      out.write("\t\t return false;\n");
      out.write("\t});\t\t\n");
      out.write("});\n");
      out.write("/* 주소 API연동 */\n");
      out.write("function execution_addr(){\n");
      out.write("\tnew daum.Postcode({\n");
      out.write("        oncomplete: function(data) {\n");
      out.write("            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.\n");
      out.write("        \t var addr = ''; // 주소 변수\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\n");
      out.write("                    addr = data.roadAddress;\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\n");
      out.write("                    addr = data.jibunAddress;\n");
      out.write("                }\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\n");
      out.write("                if(data.userSelectedType === 'R'){\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\n");
      out.write("                        extraAddr += data.bname;\n");
      out.write("                    }\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("                    }\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("                    if(extraAddr !== ''){\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\n");
      out.write("                    }\n");
      out.write("                    //주소 변수 문자열과 참고항목 문자열 합치기\n");
      out.write("                    addr += extraAddr;\n");
      out.write("                \n");
      out.write("                } else {\n");
      out.write("                    addr += ' ';\n");
      out.write("                }\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("                document.getElementById('zipcode').value = data.zonecode;\n");
      out.write("           \t\tdocument.getElementById('addr_1').value = addr;\n");
      out.write("           \t \t$('#addr_2').attr(\"readonly\",false);\n");
      out.write("            \t// 커서를 상세주소 필드로 이동한다.\n");
      out.write("           \t\t document.getElementById('addr_2').focus();\n");
      out.write("        }\n");
      out.write("    }).open(); \n");
      out.write("}\n");
      out.write("//요청이 완료되는 시점에 로딩바를 감춘다\n");
      out.write("function edit(){\t\n");
      out.write("\t// 주소+ 상세주소 연결\n");
      out.write("\tvar addr_1 = $('#addr_1').val();\n");
      out.write("\tvar addr_2 = $('#addr_2').val();\n");
      out.write("\t\n");
      out.write("\tvar addr= addr_1 + \" \"+addr_2;\n");
      out.write("\tdocument.getElementById('addr').value = addr;\n");
      out.write("\t\n");
      out.write("\t//로딩바 시작\n");
      out.write("\t$(\"#loader\").addClass(\"loader\"); //class 동적 적용\n");
      out.write("\t\n");
      out.write("\t//form 태그의 파라미터들을 전송할수있는 상태로 둬야  data키값에 form 자체를 넣을 수 있다.\n");
      out.write("\tvar formData = $(\"#member_form\").serialize(); //전부 문자열화 시킨다!!\n");
      out.write("\t\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/shop/member/memberUpdate\",\n");
      out.write("\t\ttype:\"post\",\n");
      out.write("\t\tdata:formData,\n");
      out.write("\t\tsuccess:function(responseData){\n");
      out.write("\t\t\t//서버로부터 완료 응답을 받으면 로딩바 효과를 중단!!\n");
      out.write("\t\t\t$(\"#loader\").removeClass(\"loader\"); //class 동적 제거\n");
      out.write("\t\t\talert(responseData.msg)\n");
      out.write("\t\t\tlocation.href=responseData.url;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\t\t\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Page Preloder -->\n");
      out.write("\n");
      out.write(" <!-- Offcanvas Menu Begin -->\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\n");
      out.write("        <div class=\"offcanvas__close\">+</div>\n");
      out.write("        <ul class=\"offcanvas__widget\">\n");
      out.write("            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("            <li><a href=\"/shop/cart/list\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                <div class=\"tip\">2</div>\n");
      out.write("            </a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"offcanvas__logo\">\n");
      out.write("            <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\n");
      out.write("        <div class=\"offcanvas__auth\">\n");
      out.write("            <a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("            <a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Offcanvas Menu End -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-3 col-lg-2\">\n");
      out.write("                    <div class=\"header__logo\">\n");
      out.write("                        <a href=\"/\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xl-6 col-lg-7\">\n");
      out.write("                    <nav class=\"header__menu\">\n");
      out.write("                        <ul>\n");
      out.write("                        \t<li></li>\n");
      out.write("                            <li class=\"active\"><a href=\"/\">Home</a></li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">옷</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=1\">패딩</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=2\">나시</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=3\">점프수트</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=4\">원피스</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">사료</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=5\">연어</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=6\">소고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=7\">양고기</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=8\">닭고기</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">간식</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=9\">츄잉껌</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=10\">츄르</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=11\">소시지</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=12\">육포말이</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"/shop/product/listAll\">악세서리</a>\n");
      out.write("                                <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=13\">모자</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=14\">목걸이</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=15\">펫스텝</a></li>\n");
      out.write("                                    <li><a href=\"/shop/product/list?subcategory_id=16\">철망</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <!-- <li><a href=\"/\">Shop</a></li> -->\n");
      out.write("                            <li><a href=\"/shop/cart/list\">Cart</a>\n");
      out.write("                               <!--  <ul class=\"dropdown\">\n");
      out.write("                                    <li><a href=\"./product-details.html\">Product Details</a></li>\n");
      out.write("                                     <li><a href=\"/shop/cart/list\">Cart</a></li>\n");
      out.write("                                    <li><a href=\"./checkout.html\">Checkout</a></li>\n");
      out.write("                                    <li><a href=\"./blog-details.html\">Blog Details</a></li>\n");
      out.write("                            <li><a href=\"./blog.html\">Blog</a></li>\n");
      out.write("                            <li><a href=\"./contact.html\">Contact</a></li>\n");
      out.write("                                </ul> -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"col-lg-3\">\n");
      out.write("                    <div class=\"header__right\">\n");
      out.write("                        <div class=\"header__right__auth\">\n");
      out.write("                            ");
if(session.getAttribute("member")==null){ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/loginForm\">Login</a>\n");
      out.write("                            \t<a href=\"/shop/member/registForm\">Register</a>\n");
      out.write("            \t\t\t\t");
}else{ 
      out.write("\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/logout\">LogOut</a>\n");
      out.write("            \t\t\t\t\t<a href=\"/shop/member/mypage_order\">MyPage</a>\n");
      out.write("        \t\t\t\t\t");
} 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <ul class=\"header__right__widget\">\n");
      out.write("                            <li><span class=\"icon_search search-switch\"></span></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_heart_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon_bag_alt\"></span>\n");
      out.write("                                <div class=\"tip\">2</div>\n");
      out.write("                            </a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"canvas__open\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Section End -->");
      out.write("\n");
      out.write("\t<!-- 사이트 이동경로 시작 -->\n");
      out.write("    <div class=\"breadcrumb-option\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"breadcrumb__links\">\n");
      out.write("                        <a href=\"/shop/member/mypage_order\"><i class=\"fa fa-home\"></i> Mypage</a>\n");
      out.write("                        <span>Profile</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 사이트 이동경로 종료 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 프로필 폼 시작  -->\n");
      out.write("\t<section class=\"blog-details spad\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-2\">\n");
      out.write("\t\t\t\t\t<div class=\"blog__sidebar\">\n");
      out.write("\t\t\t\t\t\t<div class=\"blog__sidebar__item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4>My Page</h4>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/shop/member/mypage_order\">주문내역 </a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/shop/member/mypage_profile\">계정관리 </a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/shop/member/mypage_delete\">회원탈퇴 </a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 col-md-9\">\n");
      out.write("\t\t\t\t\t<form class=\"checkout__form\" id=\"member_form\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\" >\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5>프로필</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>아이디</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"user_id\" class=\"user_id\"  value=\"");
      out.print(member.getUser_id());
      out.write("\" readonly>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>이름</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"name\"  value=\"");
      out.print(member.getName() );
      out.write("\" readonly> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>변경하실 비밀번호<span class=\"final_password_ck\" >　비밀번호를 입력해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"password\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>비밀번호 확인\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pwdck_1\">　비밀번호가 일치합니다.</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pwdck_2\">　비밀번호가 일치하지 않습니다.</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"final_pwdck_ck\">　비밀번호 확인을 입력해주세요</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"pwdCheck\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>이메일 주소<span class=\"final_email_id_ck\">　이메일 주소를 입력해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email_id\" class=\"email_id\" value=\"");
      out.print(member.getEmail_id());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>도메인<span class=\"final_email_server_ck\">　도메인을 선택해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"email_server\" class=\"email_server\" value=\"");
      out.print(member.getEmail_server());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													String[] domains = {"gmail.com","naver.com","hanmail.net","nate.com"};
												
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option disabled value=\"select\">선택</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
for(String domain:domains){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(domain );
      out.write('"');
      out.write(' ');
if(domain.equals(member.getEmail_server())){
      out.write("selected");
}
      out.write('>');
      out.print(domain );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>전화번호<span class=\"final_phone_ck\">　전화번호를 입력해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"phone\" class=\"phone\" value=\"");
      out.print(member.getPhone());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-md-6 col-sm-6\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>우편번호<span class=\"final_zipcode_ck\">　우편번호를 입력해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"zipcode\" class=\"zipcode\" name=\"zipcode\" readonly=\"readonly\" value=\"");
      out.print(member.getZipcode());
      out.write("\">                                   \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-md-6 col-sm-6\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p> 　</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"address_button\" onclick=\"execution_addr()\" value=\"우편번호 검색\"  >                              \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkout__form__input\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>주소<span class=\"final_addr_ck\">　주소를 입력해주세요</span></p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"addr_1\" readonly=\"readonly\" value=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"addr_2\" class=\"addr_2\" readonly=\"readonly\" value=\"");
      out.print(member.getAddr());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"addr\" id=\"addr\" name=\"addr\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"site-btn\" id=\"edit\" value=\"수정\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!-- 프로필 폼 종료 -->\n");
      out.write("\t\n");
      out.write("\n");
      out.write("<!-- Footer Section Begin -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-7\">\n");
      out.write("                <div class=\"footer__about\">\n");
      out.write("                    <div class=\"footer__logo\">\n");
      out.write("                        <a href=\"./index.html\"><img src=\"/resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt\n");
      out.write("                    cilisis.</p>\n");
      out.write("                    <div class=\"footer__payment\">\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-1.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-2.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-3.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-4.png\" alt=\"\"></a>\n");
      out.write("                        <a href=\"#\"><img src=\"/resources/img/payment/payment-5.png\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-5\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Quick links</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">About</a></li>\n");
      out.write("                        <li><a href=\"#\">Blogs</a></li>\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-md-3 col-sm-4\">\n");
      out.write("                <div class=\"footer__widget\">\n");
      out.write("                    <h6>Account</h6>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">My Account</a></li>\n");
      out.write("                        <li><a href=\"#\">Orders Tracking</a></li>\n");
      out.write("                        <li><a href=\"#\">Checkout</a></li>\n");
      out.write("                        <li><a href=\"#\">Wishlist</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-4 col-md-8 col-sm-8\">\n");
      out.write("                <div class=\"footer__newslatter\">\n");
      out.write("                    <h6>NEWSLETTER</h6>\n");
      out.write("                    <form action=\"#\">\n");
      out.write("                        <input type=\"text\" placeholder=\"Email\">\n");
      out.write("                        <button type=\"submit\" class=\"site-btn\">Subscribe</button>\n");
      out.write("                    </form>\n");
      out.write("                    <div class=\"footer__social\">\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-youtube-play\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                <div class=\"footer__copyright__text\">\n");
      out.write("                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a></p>\n");
      out.write("                </div>\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("<!-- Footer Section End -->\n");
      out.write("\n");
      out.write("<!-- Search Begin -->\n");
      out.write("<div class=\"search-model\">\n");
      out.write("    <div class=\"h-100 d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"search-close-switch\">+</div>\n");
      out.write("        <form class=\"search-model-form\">\n");
      out.write("            <input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Search End -->");
      out.write('\n');
      out.write("\n");
      out.write("<!-- Js Plugins -->\n");
      out.write("<script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/mixitup.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.countdown.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.slicknav.js\"></script>\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/jquery.nicescroll.min.js\"></script>\n");
      out.write("<script src=\"/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
